### ISSUE TITLE
Runtime Error for both basic model & reversible model

### ISSUE THREAD

**Issue by ghost** [matthewjmackay/reversible-rnn#1]
Dear Matthew, for having a problem to get results from your REVRNN code

Hi, I want to use your code for making an application for my project, but there is a problem.
When I clone your github and make virtual environment for using your both normal model and reversible model, an error message occurred when the code was executed.

Basic Model Error (**python train.py --model lstm**) 
```
/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/modules/module.py:477: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters().
  result = self.forward(*input, **kwargs)
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    global_step = train(global_step)
  File "train.py", line 168, in train
    output_dict = model(data, hidden)
  File "/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/jhkim/revrnn/language_modelling/baselines/model.py", line 75, in forward
    raw_output, new_h = rnn(raw_output, hidden[l])
  File "/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/jhkim/revrnn/language_modelling/baselines/weight_drop.py", line 45, in forward
    return self.module.forward(*args)
  File "/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 192, in forward
    output, hidden = func(input, self.all_weights, hx, batch_sizes)
  File "/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 324, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 288, in forward
    dropout_ts)
RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS
```

Reversible Model Error (**python train.py --model revlstm --use_buffers**)
```
/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "train.py", line 218, in <module>
    global_step = train(global_step)
  File "train.py", line 172, in train
    loss.backward()
  File "/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/jhkim/miniconda3/envs/rev-rnn-env/lib/python3.6/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Function ConvertToFloatBackward returned an invalid gradient at index 0 - expected type torch.cuda.IntTensor but got torch.cuda.FloatTensor
```

Environment 1 : ubuntu 18.04 python 3.6 RTX 2080 ti cuda-8.0 cudnn 7
Environment 2 : ubuntu 18.04 python 3.6 RTX 2080 ti cuda-8.0 cudnn 5

Both train.py came from language_modelling. Can we discuss this issue together for better application?

**Comment by matthewmackay** [comment]
Hi jhkim, thanks for opening an issue. I haven't seen this error myself, but I suspect it might come from using the wrong version of PyTorch. Could you check if you are using Python3 and Pytorch v0.4.0?
